LOGIN = "LOGIN"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILED = "LOGIN_FAILED"

REGISTER = "REGISTER"
REGISTER_SUCCESS = "REGISTER_SUCCESS"
REGISTER_FAILED = "REGISTER_FAILED"

PING = "PING"
PONG = "PONG"

MATCHMAKE = "MATCHMAKE"
MATCH_FOUND = "MATCH_FOUND"
WAITING_FOR_PLAYER = "WAITING_FOR_PLAYER"

ROOM_WAITING_CREATED = "ROOM_WAITING_CREATED"

CREATE_ROOM = "CREATE_ROOM"
CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS"
CREATE_ROOM_FAILED = "CREATE_ROOM_FAILED"

GET_ROOM_LIST = "GET_ROOM_LIST"
ROOM_LIST_DATA = "ROOM_LIST_DATA"

JOIN_ROOM = "JOIN_ROOM"
JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS"
JOIN_ROOM_FAILED = "JOIN_ROOM_FAILED"

START_PLACEMENT = "START_PLACEMENT"
PLACEMENT_START = "PLACEMENT_START"

PLACE_SHIPS = "PLACE_SHIPS"
PLACE_SHIPS_SUCCESS = "PLACE_SHIPS_SUCCESS"
PLACE_SHIPS_ERROR = "PLACE_SHIPS_ERROR"

READY = "READY"
WAITING_OPPONENT_READY = "WAITING_OPPONENT_READY"
GAME_START = "GAME_START"

FIRE = "FIRE"
FIRE_RESULT = "FIRE_RESULT"
OPPONENT_FIRE_RESULT = "OPPONENT_FIRE_RESULT"
TURN_UPDATE = "TURN_UPDATE"
GAME_OVER = "GAME_OVER"
REMATCH_MATCHED = "REMATCH_MATCHED"
REMATCH_WAITING = "REMATCH_WAITING"
REMATCH_REQUEST = "REMATCH_REQUEST"
FORFEIT = "FORFEIT"

JOIN_SPECTATOR = "JOIN_SPECTATOR"
SPECTATOR_JOINED = "SPECTATOR_JOINED"
SPECTATOR_UPDATE = "SPECTATOR_UPDATE"

GET_LEADERBOARD = "GET_LEADERBOARD"
LEADERBOARD_DATA = "LEADERBOARD_DATA"

GET_REPLAY_LIST = "GET_REPLAY_LIST"
REPLAY_LIST_DATA = "REPLAY_LIST_DATA"

GET_REPLAY_DETAIL = "GET_REPLAY_DETAIL"
REPLAY_DETAIL_DATA = "REPLAY_DETAIL_DATA"

LEAVE_ROOM = "LEAVE_ROOM"
ROOM_UPDATED = "ROOM_UPDATED"

ERROR = "ERROR"